
'use client';

import type { ReactNode } from 'react';
import { createContext, useContext, useState, useCallback } from 'react';

type Language = 'en' | 'ru';

interface Translations {
  [lang: string]: {
    [key: string]: string;
  };
}

const translations: Translations = {
  en: {
    'appHeader.myAccount': 'My Account',
    'appHeader.profile': 'Profile',
    'appHeader.settingsLink': 'Settings',
    'appHeader.logout': 'Log out',
    'appHeader.language': 'Language',
    'appHeader.lang.en': 'English (EN)',
    'appHeader.lang.ru': 'Russian (RU)',
    'appHeader.lang.current': 'EN',
    'appHeader.toggleSidebar': 'Toggle sidebar',

    'nav.dashboard': 'Dashboard',
    'nav.myTests': 'My Tests',
    'nav.myTemplates': 'My Templates', // Corrected
    'nav.newTest': 'New Test',
    'nav.newTemplate': 'New Template', // Corrected
    'nav.settings': 'Settings',
    'nav.adminPanel': 'Admin Panel',
    'nav.createNew': 'Create New',

    'dashboard.pageTitle': 'Dashboard',
    'dashboard.myTests.heading': 'My Tests',
    'dashboard.myTests.create': 'Create New Test',
    'dashboard.myTests.noTests.title': 'No tests created yet',
    'dashboard.myTests.noTests.description': 'Start by creating your first masterpiece!',
    'dashboard.myTests.noTests.button': 'Create Your First Test',
    'dashboard.myPageTemplates.heading': 'My Page Templates',
    'dashboard.myPageTemplates.create': 'Create New Page Template',
    'dashboard.myPageTemplates.noPageTemplates.title': 'No page templates created yet',
    'dashboard.myPageTemplates.noPageTemplates.description': 'Build reusable page designs for your quizzes.',
    'dashboard.myPageTemplates.noPageTemplates.button': 'Create Your First Page Template',
    'dashboard.editTest': 'Edit Test',
    'dashboard.editPageTemplate': 'Edit Page Template',

    'myTests.pageTitle': 'My Tests',
    'myTests.create': 'Create New Test',
    'myTests.noTests.title': "You haven't created any tests yet.",
    'myTests.noTests.description': 'Click the button below to start building your first quiz!',
    'myTests.noTests.button': 'Create Your First Test',
    'myTests.edit': 'Edit',
    'myTests.viewResults': 'View Results',
    'myTests.questionsLabel': 'questions',
    'myTests.statusLabel': 'Status',
    'myTests.lastModifiedLabel': 'Last modified',

    'myPageTemplates.pageTitle': 'My Templates', 
    'myPageTemplates.create': 'Create New Template', 
    'myPageTemplates.noPageTemplates.title': "You haven't created any templates yet.",
    'myPageTemplates.noPageTemplates.description': 'Page templates help you build quizzes faster with consistent page designs.',
    'myPageTemplates.noPageTemplates.button': 'Create Your First Template',
    'myPageTemplates.edit': 'Edit Template',
    'myPageTemplates.usageCountLabel': 'Used',
    'myPageTemplates.timesLabel': 'times',
    'myPageTemplates.lastModifiedLabel': 'Last modified',

    'settings.pageTitle': 'Settings',

    'editor.defaultTestName': 'My Awesome Quiz',
    'editor.defaultTestNameExisting': 'Test {{testId}}',
    'editor.defaultTestNameFromTemplate': 'Quiz from {{templateName}}',
    'editor.defaultEndMessage': 'Congratulations! Score: {{score}}/{{total}}.',
    'editor.quizTitlePlaceholder': 'Quiz Title',
    'editor.pageTitleNew': 'Create New Test',
    'editor.pageTitleEditing': 'Editing: {{testNameOrId}}',
    'editor.pageTitleExisting': 'Editing Test: {{testNameOrId}}',
    'editor.refreshPreview': 'Refresh Preview',
    'editor.fullScreenPreview': 'Full Screen Preview',
    'editor.saveTest': 'Save Test',
    'editor.unsavedDraftTooltip': 'Unsaved local draft exists. Save to clear.',
    'editor.config.title': 'Test Configuration & Page Style',
    'editor.config.description': 'Define test name, select a page style (template), and set the quiz end message.',
    'editor.config.testNameLabel': 'Test Name',
    'editor.config.testNamePlaceholder': 'e.g., General Knowledge',
    'editor.config.templateLabel': 'Page Style Template',
    'editor.config.selectTemplatePlaceholder': 'Select a page style template',
    'editor.config.templateDescriptionHint': 'Description: {{description}}',
    'editor.config.editTemplateLink': 'Edit Style',
    'editor.config.endMessageLabel': 'Quiz End Message',
    'editor.config.endMessagePlaceholder': 'e.g., Congrats! Score: {{score}}/{{total}}',
    'editor.config.endMessageHint': 'The template script will replace {{score}} and {{total}}.',
    'editor.config.embedTitle': 'Embed Your Test',
    'editor.config.embedDescription': 'After saving, embed code will appear here (using test ID).',
    'editor.preview.title': 'Live Preview (Powered by Selected Template)',
    'editor.preview.description': 'Interactive preview using the selected page style template and your question data.',
    'editor.questions.title': 'Questions Data',
    'editor.questions.description': 'Add and manage questions data. The selected template handles rendering.',
    'editor.questions.addQuestion': 'Add Question',
    'editor.questions.noQuestions': 'No questions added yet.',
    'editor.questions.addFirstQuestion': 'Add First Question',
    'editor.questions.questionLabel': 'Question {{number}}',
    'editor.questions.questionTypeLabel': 'Question Type',
    'editor.questions.questionTextLabel': 'Question Text',
    'editor.questions.questionTextPlaceholder': 'Enter question text',
    'editor.questions.optionsLabel': 'Options:',
    'editor.questions.markIncorrect': 'Mark as incorrect',
    'editor.questions.markCorrect': 'Mark as correct',
    'editor.questions.optionTextPlaceholder': 'Option text',
    'editor.questions.optionImageUrlPlaceholder': 'Image URL (optional)',
    'editor.questions.removeOption': 'Remove option',
    'editor.questions.addOption': 'Add Option',
    'editor.questions.matchingPairsLabel': 'Matching Pairs:',
    'editor.questions.addMatchPair': 'Add Pair',
    'editor.questions.matchPromptPlaceholder': 'Prompt Text',
    'editor.questions.matchTargetPlaceholder': 'Target Text',
    'editor.questions.removeMatchPair': 'Remove Pair',
    'editor.questions.dragItemsLabel': 'Draggable Items:',
    'editor.questions.addDragItem': 'Add Item',
    'editor.questions.dragItemPlaceholder': 'Draggable Item Text',
    'editor.questions.removeDragItem': 'Remove Item',
    'editor.questions.dropTargetsLabel': 'Drop Targets:',
    'editor.questions.addDropTarget': 'Add Target',
    'editor.questions.dropTargetPlaceholder': 'Drop Target Text (optional, for label)',
    'editor.questions.removeDropTarget': 'Remove Target',
    'editor.questions.selectCorrectDragItem': 'Select Correct Draggable Item',
    'editor.questions.noCorrectDragItem': 'None (visual only in template)',
    'editor.questions.configNotAvailable': 'Configuration for this question type is not yet fully available.',
    'editor.newQuestionText': 'New Question {{number}}',
    'editor.optionPlaceholder': 'Option {{letter}}',
    'editor.newOptionText': 'New Option {{number}}',
    'editor.toast.saveSuccessTitle': 'Test Data Logged',
    'editor.toast.saveSuccessDescription': 'Test configuration has been logged to the console.',
    'editor.toast.saveSuccessTitleExisting': 'Existing Test Data Logged',
    'editor.toast.saveSuccessDescriptionExisting': 'Test {{testId}} configuration logged to console.',
    'editor.toast.draftRestoredTitle': 'Draft Restored',
    'editor.toast.draftRestoredDescriptionNew': 'Your unsaved new test draft has been loaded.',
    'editor.toast.draftRestoredDescriptionExisting': 'Unsaved draft for test "{{testName}}" loaded.',
    'editor.toast.popupBlockedTitle': 'Popup Blocked',
    'editor.toast.popupBlockedDescription': 'Please allow popups for this site to use full screen preview.',
    'editor.toast.templateNotFoundTitle': 'Page Style Template Not Found',
    'editor.toast.templateNotFoundDescription': 'The page style template "{{templateId}}" was not found. Loaded default blank canvas.',
    'editor.toast.templateLoadErrorTitle': 'Template Load Error',
    'editor.toast.templateLoadErrorDescription': 'Could not load template "{{templateId}}". Starting with a blank canvas.',

    'pageTemplateEditor.new.pageTitle': 'New Page Style Template',
    'pageTemplateEditor.new.pageTitleFromSource': 'New Page Style Template (from {{sourceName}})',
    'pageTemplateEditor.edit.pageTitle': 'Edit Page Style Template: {{templateIdOrName}}',
    'pageTemplateEditor.updatePreview': 'Update Preview',
    'pageTemplateEditor.saveTemplate': 'Save Page Style Template',
    'pageTemplateEditor.unsavedDraftTooltip': 'Unsaved local draft exists. Save to clear.',
    'pageTemplateEditor.details.title': 'Page Style Template Details & Engine',
    'pageTemplateEditor.details.description': 'Define the HTML structure, CSS style, and JavaScript quiz engine of your reusable page template.',
    'pageTemplateEditor.details.nameLabel': 'Template Name',
    'pageTemplateEditor.details.namePlaceholder': 'e.g., Modern MCQ Page Style',
    'pageTemplateEditor.details.loadedNamePlaceholder': 'Page Style Template {{templateId}}',
    'pageTemplateEditor.details.descriptionLabel': 'Description (Optional)',
    'pageTemplateEditor.details.descriptionPlaceholder': 'A brief description of what this page style template is best for...',
    'pageTemplateEditor.details.htmlLabel': 'Page HTML Structure (Includes JS Quiz Engine)',
    'pageTemplateEditor.details.htmlPlaceholder': 'Enter page template HTML, including <script> tags for all quiz logic...',
    'pageTemplateEditor.details.htmlHint': 'Include <script> tags for all JS quiz logic. The script should read data from #quiz-data, #quiz-name-data, #quiz-end-message-data. Placeholders like {{template_title_placeholder}} can be used for template preview here.',
    'pageTemplateEditor.details.cssLabel': 'Page CSS Styles',
    'pageTemplateEditor.details.cssPlaceholder': 'Enter page template CSS...\n/* Style your page template elements */\n/* Add your CSS animations here */',
    'pageTemplateEditor.details.cssHint': 'Your CSS will be injected into the preview. Tailwind CSS is also available there. Use CSS variables from globals.css (e.g., hsl(var(--primary))) for theming.',
    'pageTemplateEditor.preview.titlePane': 'Page Style Template Preview',
    'pageTemplateEditor.preview.descriptionPane': 'This is how your page template structure will look with sample content.',
    'pageTemplateEditor.preview.iframeTitle': 'Page Style Template Preview',
    'pageTemplateEditor.preview.sampleTitle': 'Sample Template Title',
    'pageTemplateEditor.preview.sampleQuestion': 'This is where a sample question might appear.',
    'pageTemplateEditor.preview.sampleOption1': 'Sample Option A',
    'pageTemplateEditor.preview.sampleOption2': 'Sample Option B',
    'pageTemplateEditor.toast.saveSuccessTitle': 'Page Style Template Saved (Mock)',
    'pageTemplateEditor.toast.saveSuccessDescription': 'Page Style Template "{{templateName}}" data logged to console.',
    'pageTemplateEditor.toast.saveSuccessTitleExisting': 'Existing Page Style Template Saved (Mock)',
    'pageTemplateEditor.toast.saveSuccessDescriptionExisting': 'Page Style Template {{templateName}} data logged to console.',
    'pageTemplateEditor.toast.draftRestoredTitle': 'Draft Restored',
    'pageTemplateEditor.toast.draftRestoredDescriptionNew': 'Your unsaved new page style template draft has been loaded.',
    'pageTemplateEditor.toast.draftRestoredDescriptionExisting': 'Unsaved draft for template "{{templateName}}" loaded.',
    'pageTemplateEditor.toast.loadErrorTitle': 'Load Error',
    'pageTemplateEditor.toast.loadErrorDescription': 'Could not load template "{{templateId}}". Loaded default blank canvas.',

    'pageTemplates.explore.pageTitle': 'Explore Page Style Templates', 
    'pageTemplates.explore.createButton': 'Create New Template', 
    'pageTemplates.explore.useThisTemplate': 'Use This Style',
    'pageTemplates.explore.preview': 'Edit Page Style',
    'pageTemplates.explore.duplicate': 'Duplicate Style',
    'pageTemplates.explore.noTemplates.title': 'No Page Style Templates Available Yet',
    'pageTemplates.explore.noTemplates.description': 'Be the first to create a stunning page style template for QuizSmith!',
    'pageTemplates.explore.noTemplates.button': 'Create Your First Page Style Template',

    'testResults.pageTitle': 'Results: {{testId}}',
    'testResults.summaryTitle': 'Test Summary',
    'testResults.summaryDescription': 'Detailed results for test ID: {{testId}}. This feature is under development.',
    'testResults.comingSoon': 'Detailed test results and analytics will be available here soon.',
    'testResults.checkBack': 'Please check back later!',

    'adminPanel.pageTitle': 'Admin Panel',
    'adminPanel.storage.title': 'Storage Configuration',
    'adminPanel.storage.description': 'Select and configure permanent storage options for the application. (Note: This is a UI placeholder. Backend implementation is required for full functionality).',
    'adminPanel.storage.selectLabel': 'Choose Storage Type:',
    'adminPanel.storage.sqlite.label': 'SQLite',
    'adminPanel.storage.sqlite.description': 'Local file-based database. Good for development or small single-server deployments.',
    'adminPanel.storage.sqlite.pathLabel': 'Database File Path',
    'adminPanel.storage.sqlite.pathPlaceholder': '/path/to/your/database.sqlite',
    'adminPanel.storage.mysql.label': 'MySQL',
    'adminPanel.storage.mysql.description': 'Robust relational database. Suitable for larger applications.',
    'adminPanel.storage.mysql.hostLabel': 'Host',
    'adminPanel.storage.mysql.portLabel': 'Port',
    'adminPanel.storage.mysql.dbNameLabel': 'Database Name',
    'adminPanel.storage.mysql.userLabel': 'Username',
    'adminPanel.storage.mysql.passwordLabel': 'Password',
    'adminPanel.storage.firestore.label': 'Firebase Firestore',
    'adminPanel.storage.firestore.description': 'Scalable NoSQL cloud database. Recommended for Next.js applications.',
    'adminPanel.storage.firestore.projectIdLabel': 'Project ID',
    'adminPanel.storage.firestore.clientEmailLabel': 'Client Email',
    'adminPanel.storage.firestore.privateKeyLabel': 'Private Key (JSON)',
    'adminPanel.storage.firestore.privateKeyPlaceholder': 'Paste your Firebase service account private key JSON here...',
    'adminPanel.storage.saveButton': 'Save Configuration',
    'adminPanel.toast.saveConfigTitle': 'Configuration Update',
    'adminPanel.toast.saveConfigDescription': 'This feature is not yet implemented. Backend development is required.',
    'adminPanel.toast.notImplementedTitle': 'Feature Not Implemented',
    'adminPanel.toast.notImplementedDescription': '{{featureName}} functionality is not yet available.',
    'adminPanel.logs.title': 'Application Logs',
    'adminPanel.logs.description': 'View system and application logs. (Placeholder UI)',
    'adminPanel.logs.placeholder': 'Log entries would appear here...\n[INFO] 2023-10-27 10:00:00 - Application started.\n[WARN] 2023-10-27 10:05:23 - User login attempt failed.\n...',
    'adminPanel.logs.refreshButton': 'Refresh Logs',
    'questionType.multiple-choice-text': 'Multiple Choice (Text)',
    'questionType.multiple-choice-image': 'Multiple Choice (Image)',
    'questionType.matching-text-text': 'Matching (Text-to-Text)',
    'questionType.drag-and-drop-text-text': 'Drag & Drop (Text-on-Text)',
  },
  ru: {
    'appHeader.myAccount': 'Мой аккаунт',
    'appHeader.profile': 'Профиль',
    'appHeader.settingsLink': 'Настройки',
    'appHeader.logout': 'Выйти',
    'appHeader.language': 'Язык',
    'appHeader.lang.en': 'Английский (EN)',
    'appHeader.lang.ru': 'Русский (RU)',
    'appHeader.lang.current': 'RU',
    'appHeader.toggleSidebar': 'Переключить боковую панель',

    'nav.dashboard': 'Панель',
    'nav.myTests': 'Мои тесты',
    'nav.myTemplates': 'Мои шаблоны', // Corrected
    'nav.newTest': 'Новый тест',
    'nav.newTemplate': 'Новый шаблон', // Corrected
    'nav.settings': 'Настройки',
    'nav.adminPanel': 'Панель администратора',
    'nav.createNew': 'Создать',

    'dashboard.pageTitle': 'Панель',
    'dashboard.myTests.heading': 'Мои тесты',
    'dashboard.myTests.create': 'Создать новый тест',
    'dashboard.myTests.noTests.title': 'Тесты еще не созданы',
    'dashboard.myTests.noTests.description': 'Начните с создания вашего первого шедевра!',
    'dashboard.myTests.noTests.button': 'Создать первый тест',
    'dashboard.myPageTemplates.heading': 'Мои шаблоны страниц',
    'dashboard.myPageTemplates.create': 'Создать новый шаблон страницы',
    'dashboard.myPageTemplates.noPageTemplates.title': 'Шаблоны страниц еще не созданы',
    'dashboard.myPageTemplates.noPageTemplates.description': 'Создавайте многоразовые дизайны страниц для ваших викторин.',
    'dashboard.myPageTemplates.noPageTemplates.button': 'Создать первый шаблон страницы',
    'dashboard.editTest': 'Редактировать тест',
    'dashboard.editPageTemplate': 'Редактировать шаблон страницы',

    'myTests.pageTitle': 'Мои тесты',
    'myTests.create': 'Создать новый тест',
    'myTests.noTests.title': 'Вы еще не создали ни одного теста.',
    'myTests.noTests.description': 'Нажмите кнопку ниже, чтобы начать создавать свою первую викторину!',
    'myTests.noTests.button': 'Создать свой первый тест',
    'myTests.edit': 'Редактировать',
    'myTests.viewResults': 'Смотреть результаты',
    'myTests.questionsLabel': 'вопросов',
    'myTests.statusLabel': 'Статус',
    'myTests.lastModifiedLabel': 'Последнее изменение',

    'myPageTemplates.pageTitle': 'Мои шаблоны', 
    'myPageTemplates.create': 'Создать новый шаблон', 
    'myPageTemplates.noPageTemplates.title': 'Вы еще не создали ни одного шаблона.',
    'myPageTemplates.noPageTemplates.description': 'Шаблоны страниц помогут вам быстрее создавать викторины с единым дизайном страниц.',
    'myPageTemplates.noPageTemplates.button': 'Создать свой первый шаблон',
    'myPageTemplates.edit': 'Редактировать шаблон',
    'myPageTemplates.usageCountLabel': 'Использовано',
    'myPageTemplates.timesLabel': 'раз',
    'myPageTemplates.lastModifiedLabel': 'Последнее изменение',

    'settings.pageTitle': 'Настройки',

    'editor.defaultTestName': 'Моя классная викторина',
    'editor.defaultTestNameExisting': 'Тест {{testId}}',
    'editor.defaultTestNameFromTemplate': 'Викторина из шаблона: {{templateName}}',
    'editor.defaultEndMessage': 'Поздравляем! Результат: {{score}}/{{total}}.',
    'editor.quizTitlePlaceholder': 'Название викторины',
    'editor.pageTitleNew': 'Создать новый тест',
    'editor.pageTitleEditing': 'Редактирование: {{testNameOrId}}',
    'editor.pageTitleExisting': 'Редактирование теста: {{testNameOrId}}',
    'editor.refreshPreview': 'Обновить предпросмотр',
    'editor.fullScreenPreview': 'Полноэкранный предпросмотр',
    'editor.saveTest': 'Сохранить тест',
    'editor.unsavedDraftTooltip': 'Существует несохраненный локальный черновик. Сохраните, чтобы очистить.',
    'editor.config.title': 'Конфигурация теста и стиль страницы',
    'editor.config.description': 'Задайте название теста, выберите стиль страницы (шаблон) и сообщение о завершении викторины.',
    'editor.config.testNameLabel': 'Название теста',
    'editor.config.testNamePlaceholder': 'например, Общие знания',
    'editor.config.templateLabel': 'Шаблон стиля страницы',
    'editor.config.selectTemplatePlaceholder': 'Выберите шаблон стиля страницы',
    'editor.config.templateDescriptionHint': 'Описание: {{description}}',
    'editor.config.editTemplateLink': 'Редактировать стиль',
    'editor.config.endMessageLabel': 'Сообщение о завершении викторины',
    'editor.config.endMessagePlaceholder': 'например, Поздравляем! Результат: {{score}}/{{total}}',
    'editor.config.endMessageHint': 'Скрипт шаблона заменит {{score}} и {{total}}.',
    'editor.config.embedTitle': 'Встроить ваш тест',
    'editor.config.embedDescription': 'После сохранения здесь появится код для встраивания (используя ID теста).',
    'editor.preview.title': 'Живой предпросмотр (на базе выбранного шаблона)',
    'editor.preview.description': 'Интерактивный предпросмотр с использованием выбранного шаблона стиля страницы и ваших данных вопросов.',
    'editor.questions.title': 'Данные вопросов',
    'editor.questions.description': 'Добавляйте и управляйте данными вопросов. Выбранный шаблон отвечает за отображение.',
    'editor.questions.addQuestion': 'Добавить вопрос',
    'editor.questions.noQuestions': 'Вопросы еще не добавлены.',
    'editor.questions.addFirstQuestion': 'Добавить первый вопрос',
    'editor.questions.questionLabel': 'Вопрос {{number}}',
    'editor.questions.questionTypeLabel': 'Тип вопроса',
    'editor.questions.questionTextLabel': 'Текст вопроса',
    'editor.questions.questionTextPlaceholder': 'Введите текст вопроса',
    'editor.questions.optionsLabel': 'Варианты:',
    'editor.questions.markIncorrect': 'Отметить как неверный',
    'editor.questions.markCorrect': 'Отметить как верный',
    'editor.questions.optionTextPlaceholder': 'Текст варианта',
    'editor.questions.optionImageUrlPlaceholder': 'URL изображения (необязательно)',
    'editor.questions.removeOption': 'Удалить вариант',
    'editor.questions.addOption': 'Добавить вариант',
    'editor.questions.matchingPairsLabel': 'Пары для сопоставления:',
    'editor.questions.addMatchPair': 'Добавить пару',
    'editor.questions.matchPromptPlaceholder': 'Текст элемента для сопоставления',
    'editor.questions.matchTargetPlaceholder': 'Текст соответствующего элемента',
    'editor.questions.removeMatchPair': 'Удалить пару',
    'editor.questions.dragItemsLabel': 'Перетаскиваемые элементы:',
    'editor.questions.addDragItem': 'Добавить элемент',
    'editor.questions.dragItemPlaceholder': 'Текст перетаскиваемого элемента',
    'editor.questions.removeDragItem': 'Удалить элемент',
    'editor.questions.dropTargetsLabel': 'Места для перетаскивания:',
    'editor.questions.addDropTarget': 'Добавить место',
    'editor.questions.dropTargetPlaceholder': 'Текст метки для места (необязательно)',
    'editor.questions.removeDropTarget': 'Удалить место',
    'editor.questions.selectCorrectDragItem': 'Выберите правильный перетаскиваемый элемент',
    'editor.questions.noCorrectDragItem': 'Нет (только визуально в шаблоне)',
    'editor.questions.configNotAvailable': 'Конфигурация для этого типа вопроса пока недоступна.',
    'editor.newQuestionText': 'Новый вопрос {{number}}',
    'editor.optionPlaceholder': 'Вариант {{letter}}',
    'editor.newOptionText': 'Новый вариант {{number}}',
    'editor.toast.saveSuccessTitle': 'Данные теста записаны',
    'editor.toast.saveSuccessDescription': 'Конфигурация теста записана в консоль.',
    'editor.toast.saveSuccessTitleExisting': 'Данные существующего теста записаны',
    'editor.toast.saveSuccessDescriptionExisting': 'Конфигурация теста {{testId}} записана в консоль.',
    'editor.toast.draftRestoredTitle': 'Черновик восстановлен',
    'editor.toast.draftRestoredDescriptionNew': 'Ваш несохраненный черновик нового теста загружен.',
    'editor.toast.draftRestoredDescriptionExisting': 'Несохраненный черновик теста "{{testName}}" загружен.',
    'editor.toast.popupBlockedTitle': 'Всплывающее окно заблокировано',
    'editor.toast.popupBlockedDescription': 'Пожалуйста, разрешите всплывающие окна для этого сайта, чтобы использовать полноэкранный предпросмотр.',
    'editor.toast.templateNotFoundTitle': 'Шаблон стиля страницы не найден',
    'editor.toast.templateNotFoundDescription': 'Шаблон стиля страницы "{{templateId}}" не найден. Загружен пустой шаблон по умолчанию.',
    'editor.toast.templateLoadErrorTitle': 'Ошибка загрузки шаблона',
    'editor.toast.templateLoadErrorDescription': 'Не удалось загрузить шаблон "{{templateId}}". Загружен пустой холст.',

    'pageTemplateEditor.new.pageTitle': 'Новый шаблон стиля страницы',
    'pageTemplateEditor.new.pageTitleFromSource': 'Новый шаблон стиля страницы (из {{sourceName}})',
    'pageTemplateEditor.edit.pageTitle': 'Редактировать шаблон стиля страницы: {{templateIdOrName}}',
    'pageTemplateEditor.updatePreview': 'Обновить предпросмотр',
    'pageTemplateEditor.saveTemplate': 'Сохранить шаблон стиля страницы',
    'pageTemplateEditor.unsavedDraftTooltip': 'Существует несохраненный локальный черновик. Сохраните, чтобы очистить.',
    'pageTemplateEditor.details.title': 'Детали и движок шаблона стиля страницы',
    'pageTemplateEditor.details.description': 'Определите структуру HTML, стиль CSS и JavaScript-движок викторины вашего многоразового шаблона страницы.',
    'pageTemplateEditor.details.nameLabel': 'Название шаблона',
    'pageTemplateEditor.details.namePlaceholder': 'например, Современный стиль страницы MCQ',
    'pageTemplateEditor.details.loadedNamePlaceholder': 'Шаблон стиля страницы {{templateId}}',
    'pageTemplateEditor.details.descriptionLabel': 'Описание (необязательно)',
    'pageTemplateEditor.details.descriptionPlaceholder': 'Краткое описание, для чего лучше всего подходит этот шаблон стиля страницы...',
    'pageTemplateEditor.details.htmlLabel': 'Структура HTML страницы (включая JS-движок викторины)',
    'pageTemplateEditor.details.htmlPlaceholder': 'Введите HTML шаблона страницы, включая теги <script> для всей логики викторины...',
    'pageTemplateEditor.details.htmlHint': 'Включите теги &lt;script&gt; для всей JS логики викторины. Скрипт должен читать данные из #quiz-data, #quiz-name-data, #quiz-end-message-data. Плейсхолдеры вроде {{template_title_placeholder}} можно использовать здесь для предпросмотра шаблона.',
    'pageTemplateEditor.details.cssLabel': 'Стили CSS страницы',
    'pageTemplateEditor.details.cssPlaceholder': 'Введите CSS шаблона страницы...\n/* Стилизуйте элементы вашего шаблона страницы */\n/* Добавьте сюда свои CSS анимации */',
    'pageTemplateEditor.details.cssHint': 'Ваш CSS будет внедрен в предпросмотр. Tailwind CSS также доступен там. Используйте CSS переменные из globals.css (например, hsl(var(--primary))) для темизации.',
    'pageTemplateEditor.preview.titlePane': 'Предпросмотр шаблона стиля страницы',
    'pageTemplateEditor.preview.descriptionPane': 'Так будет выглядеть структура вашего шаблона стиля страницы с образцом содержимого.',
    'pageTemplateEditor.preview.iframeTitle': 'Предпросмотр шаблона стиля страницы',
    'pageTemplateEditor.preview.sampleTitle': 'Пример названия шаблона',
    'pageTemplateEditor.preview.sampleQuestion': 'Здесь может отображаться пример вопроса.',
    'pageTemplateEditor.preview.sampleOption1': 'Пример варианта А',
    'pageTemplateEditor.preview.sampleOption2': 'Пример варианта Б',
    'pageTemplateEditor.toast.saveSuccessTitle': 'Шаблон стиля страницы сохранен (имитация)',
    'pageTemplateEditor.toast.saveSuccessDescription': 'Данные шаблона стиля страницы "{{templateName}}" записаны в консоль.',
    'pageTemplateEditor.toast.saveSuccessTitleExisting': 'Существующий шаблон стиля страницы сохранен (имитация)',
    'pageTemplateEditor.toast.saveSuccessDescriptionExisting': 'Данные шаблона стиля страницы {{templateName}} записаны в консоль.',
    'pageTemplateEditor.toast.draftRestoredTitle': 'Черновик восстановлен',
    'pageTemplateEditor.toast.draftRestoredDescriptionNew': 'Ваш несохраненный черновик нового шаблона стиля страницы загружен.',
    'pageTemplateEditor.toast.draftRestoredDescriptionExisting': 'Несохраненный черновик шаблона "{{templateName}}" загружен.',
    'pageTemplateEditor.toast.loadErrorTitle': 'Ошибка загрузки',
    'pageTemplateEditor.toast.loadErrorDescription': 'Не удалось загрузить шаблон "{{templateId}}". Загружен пустой шаблон по умолчанию.',

    'pageTemplates.explore.pageTitle': 'Обзор шаблонов стилей страниц', 
    'pageTemplates.explore.createButton': 'Создать новый шаблон', 
    'pageTemplates.explore.useThisTemplate': 'Использовать этот стиль',
    'pageTemplates.explore.preview': 'Редактировать стиль страницы',
    'pageTemplates.explore.duplicate': 'Дублировать стиль',
    'pageTemplates.explore.noTemplates.title': 'Доступных шаблонов стилей страниц пока нет',
    'pageTemplates.explore.noTemplates.description': 'Станьте первым, кто создаст потрясающий шаблон стиля страницы для QuizSmith!',
    'pageTemplates.explore.noTemplates.button': 'Создать свой первый шаблон стиля страницы',

    'testResults.pageTitle': 'Результаты: {{testId}}',
    'testResults.summaryTitle': 'Сводка по тесту',
    'testResults.summaryDescription': 'Подробные результаты для теста ID: {{testId}}. Эта функция находится в разработке.',
    'testResults.comingSoon': 'Подробные результаты теста и аналитика скоро будут доступны здесь.',
    'testResults.checkBack': 'Пожалуйста, зайдите позже!',

    'adminPanel.pageTitle': 'Панель администратора',
    'adminPanel.storage.title': 'Конфигурация хранилища',
    'adminPanel.storage.description': 'Выберите и настройте параметры постоянного хранилища для приложения. (Примечание: Это заглушка интерфейса. Для полной функциональности требуется разработка бэкенда).',
    'adminPanel.storage.selectLabel': 'Выберите тип хранилища:',
    'adminPanel.storage.sqlite.label': 'SQLite',
    'adminPanel.storage.sqlite.description': 'Локальная файловая база данных. Подходит для разработки или небольших односерверных развертываний.',
    'adminPanel.storage.sqlite.pathLabel': 'Путь к файлу базы данных',
    'adminPanel.storage.sqlite.pathPlaceholder': '/путь/к/вашей/базе.sqlite',
    'adminPanel.storage.mysql.label': 'MySQL',
    'adminPanel.storage.mysql.description': 'Надежная реляционная база данных. Подходит для крупных приложений.',
    'adminPanel.storage.mysql.hostLabel': 'Хост',
    'adminPanel.storage.mysql.portLabel': 'Порт',
    'adminPanel.storage.mysql.dbNameLabel': 'Имя базы данных',
    'adminPanel.storage.mysql.userLabel': 'Имя пользователя',
    'adminPanel.storage.mysql.passwordLabel': 'Пароль',
    'adminPanel.storage.firestore.label': 'Firebase Firestore',
    'adminPanel.storage.firestore.description': 'Масштабируемая облачная NoSQL база данных. Рекомендуется для приложений Next.js.',
    'adminPanel.storage.firestore.projectIdLabel': 'ID Проекта',
    'adminPanel.storage.firestore.clientEmailLabel': 'Email клиента',
    'adminPanel.storage.firestore.privateKeyLabel': 'Приватный ключ (JSON)',
    'adminPanel.storage.firestore.privateKeyPlaceholder': 'Вставьте сюда JSON приватного ключа вашего сервисного аккаунта Firebase...',
    'adminPanel.storage.saveButton': 'Сохранить конфигурацию',
    'adminPanel.toast.saveConfigTitle': 'Обновление конфигурации',
    'adminPanel.toast.saveConfigDescription': 'Эта функция еще не реализована. Требуется разработка бэкенда.',
    'adminPanel.toast.notImplementedTitle': 'Функция не реализована',
    'adminPanel.toast.notImplementedDescription': 'Функциональность "{{featureName}}" еще не доступна.',
    'adminPanel.logs.title': 'Логи приложения',
    'adminPanel.logs.description': 'Просмотр системных и прикладных логов. (Заглушка интерфейса)',
    'adminPanel.logs.placeholder': 'Записи логов будут отображаться здесь...\n[ИНФО] 2023-10-27 10:00:00 - Приложение запущено.\n[ПРЕДУПР.] 2023-10-27 10:05:23 - Неудачная попытка входа пользователя.\n...',
    'adminPanel.logs.refreshButton': 'Обновить логи',

    'questionType.multiple-choice-text': 'Один из многих (Текст)',
    'questionType.multiple-choice-image': 'Один из многих (Изображение)',
    'questionType.matching-text-text': 'Сопоставление (Текст-Текст)',
    'questionType.drag-and-drop-text-text': 'Перетаскивание (Текст-на-Текст)',
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string, replacements?: Record<string, string | number | undefined>, defaultValue?: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en');

  const setLanguage = useCallback((lang: Language) => {
    setLanguageState(lang);
  }, []);

  const t = useCallback(
    (key: string, replacements?: Record<string, string | number | undefined>, defaultValue?: string): string => {
      let translation = translations[language]?.[key] || translations.en?.[key] || defaultValue || key;
      if (replacements) {
        Object.keys(replacements).forEach((placeholder) => {
          const value = replacements[placeholder];
          if (value !== undefined) {
             translation = translation.replace(
               new RegExp(`{{\\s*${placeholder}\\s*}}`, 'g'), 
               String(value)
             );
          }
        });
      }
      return translation;
    },
    [language]
  );

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
